"""
evaluator.py
-------------
RAG Evaluation Suite using RAGAS.

Loads the synthetic golden dataset generated by scripts/generate_synthetic_dataset.py
(synthetic_golden_dataset.json) and evaluates the pipeline using the real
retrieve() and generate_draft() functions.

Usage (via main.py):
    python main.py --stage evaluate --project demo_project

Usage (standalone):
    python evaluator.py --project demo_project
    python evaluator.py --project demo_project --dataset path/to/synthetic_golden_dataset.json
"""

import os
import sys
import time
import json
import argparse
from pathlib import Path
from datetime import datetime, timezone

import pandas as pd
from dotenv import load_dotenv

from datasets import Dataset
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from ragas.run_config import RunConfig

from scripts.config import settings
from scripts.chunker import MAX_TOKENS, OVERLAP_TOKENS

from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_recall,
    context_precision,
)

# Real pipeline functions
from scripts.retriever import retrieve
from scripts.redactor import generate_draft
from scripts.utils.paths import get_project_paths

load_dotenv()

# ─────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────

SYSTEM_CONFIG = {
    "chunk_max_tokens": MAX_TOKENS,
    "chunk_overlap_tokens": OVERLAP_TOKENS,
    "top_k": settings.retriever_top_k,
    "embedding_model": settings.embedding_model,
    "generation_llm_model": settings.llm_model,
    "judge_llm_model": "gpt-4o-mini",
    "chroma_collection_name": settings.chroma_collection_name,
    "pipeline_version": "rag_eval_v1.0.0",
}

EVAL_SECTION_NAME = "RAG Evaluation Query"

# Default filename for the synthetic golden dataset
SYNTHETIC_DATASET_FILENAME = "synthetic_golden_dataset.json"


# ─────────────────────────────────────────────────────────
# UTILS
# ─────────────────────────────────────────────────────────

def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def save_jsonl(path: str, records: list[dict]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")


def ensure_string_contexts(chunks) -> list[str]:
    """Normalise retrieved chunks to plain strings regardless of their type."""
    if not chunks:
        return []
    sanitized = []
    for chunk in chunks:
        if isinstance(chunk, str):
            text = chunk
        elif isinstance(chunk, dict):
            text = (
                chunk.get("page_content")
                or chunk.get("text")
                or chunk.get("content")
                or json.dumps(chunk, ensure_ascii=False)
            )
        elif hasattr(chunk, "page_content"):
            text = getattr(chunk, "page_content")
        elif hasattr(chunk, "content"):
            # RetrievedChunk dataclass from retriever.py
            text = getattr(chunk, "content")
        else:
            text = str(chunk)
        text = text.strip()
        if text:
            sanitized.append(text)
    return sanitized

def calculate_retrieval_ground_truth_metrics(
    item: dict,
    retrieved_chunks: list[dict],
) -> dict:
    """
    Compare retrieved chunk IDs against the expected source chunk IDs
    stored in the evaluation dataset.
    """

    if item["answerable"] is not True:
        return {
            "expected_chunks_count": 0,
            "expected_chunks_retrieved": 0,
            "retrieval_hit_at_1": None,
            "retrieval_hit_at_3": None,
            "expected_chunk_recall": None,
        }

    expected_ids: list[str] = []

    if item.get("source_chunk_id"):
        expected_ids = [item["source_chunk_id"]]

    elif item.get("source_chunk_ids"):
        expected_ids = list(item["source_chunk_ids"])

    if not expected_ids:
        return {
            "expected_chunks_count": 0,
            "expected_chunks_retrieved": 0,
            "retrieval_hit_at_1": None,
            "retrieval_hit_at_3": None,
            "expected_chunk_recall": None,
        }

    retrieved_ids = [
        chunk["chunk_id"]
        for chunk in retrieved_chunks
    ]

    expected_set = set(expected_ids)
    retrieved_set = set(retrieved_ids)

    hits = expected_set.intersection(retrieved_set)

    return {
        "expected_chunks_count": len(expected_ids),
        "expected_chunks_retrieved": len(hits),
        "retrieval_hit_at_1": int(
            bool(retrieved_ids)
            and retrieved_ids[0] in expected_set
        ),
        "retrieval_hit_at_3": int(
            any(
                chunk_id in expected_set
                for chunk_id in retrieved_ids[:3]
            )
        ),
        "expected_chunk_recall": round(
            len(hits) / len(expected_ids),
            4,
        ),
    }

# ─────────────────────────────────────────────────────────
# DATASET LOADER
# ─────────────────────────────────────────────────────────

def load_golden_dataset(json_path: Path) -> list[dict]:
    """
    Loads the synthetic golden dataset produced by
    scripts/generate_synthetic_dataset.py.

    Supports two JSON structures:

    1. Flat list:
       [
           {"eval_id": "FACT_001", "category": "factual",
            "question": "...", "ground_truth": "...", ...},
           ...
       ]

    2. Wrapped object (legacy / alternative format):
       {
           "project": "...",
           "items": [
               {"eval_id": "FACT_001", "category": "factual",
                "question": "...", "ground_truth": "...", ...},
               ...
           ]
       }

    Required fields per item: eval_id, category, answerable, question, ground_truth.
    Optional fields preserved in telemetry:
    source, source_chunk_id, source_chunk_ids,source_section, source_sections.
    """
    if not json_path.exists():
        print(f"[ERROR] Golden dataset not found: {json_path}")
        print(
            "Run first: "
            "python main.py --stage eval-generate --project <name>"
        )
        sys.exit(1)

    with open(json_path, encoding="utf-8") as f:
        raw = json.load(f)

    # Normalise to a flat list regardless of input shape
    if isinstance(raw, list):
        items = raw
    elif isinstance(raw, dict):
        items = raw.get("items", [])
    else:
        print(f"[ERROR] Unexpected JSON structure in: {json_path}")
        sys.exit(1)

    if not items:
        print(f"[ERROR] Golden dataset is empty: {json_path}")
        sys.exit(1)

    # Validate required fields
    required = {
        "eval_id",
        "category",
        "answerable",
        "question",
        "ground_truth",
    }
    invalid = []
    for i, item in enumerate(items):
        missing = required - item.keys()
        if missing:
            print(f"[WARN] Item {i} missing fields {missing} — skipping.")
            invalid.append(i)

    valid = [item for i, item in enumerate(items) if i not in invalid]
    print(f"[INFO] Loaded {len(valid)} valid items from {json_path.name}")
    return valid


# ─────────────────────────────────────────────────────────
# PIPELINE
# ─────────────────────────────────────────────────────────

def run_monitored_pipeline(
    question: str,
    chroma_dir: str,
    directives_path: Path | None,
) -> dict:
    """
    Runs the real RAG pipeline (retrieve → generate_draft) for a single
    question and captures timing + error telemetry.
    """
    
    run_log = {
        "status": "success",
        "error_message": None,
        "failed_stage": None,
        "retrieval_time_sec": 0.0,
        "generation_time_sec": 0.0,
        "total_pipeline_time_sec": 0.0,
        "contexts": [],
        "retrieved_chunks": [],
        "answer": "",
    }

    start_total = time.time()

    # ── RETRIEVAL ──────────────────────────────────────────
    try:
        start = time.time()
        raw_chunks = retrieve(query=question, chroma_dir=chroma_dir)

        run_log["contexts"] = ensure_string_contexts(raw_chunks)

        run_log["retrieved_chunks"] = [
            {
                "chunk_id": chunk.chunk_id,
                "source_file": chunk.source_file,
                "section_title": chunk.section_title,
                "section_level": chunk.section_level,
                "parent_section": chunk.parent_section,
                "is_continuation": chunk.is_continuation,
                "has_table": chunk.has_table,
                "relevance_score": chunk.relevance_score,
                "content": chunk.content,
            }
            for chunk in raw_chunks
        ]

        run_log["retrieval_time_sec"] = round(time.time() - start, 3)

    except Exception as e:
        run_log.update(status="failed", failed_stage="retrieval", error_message=str(e))
        run_log["total_pipeline_time_sec"] = round(time.time() - start_total, 3)
        return run_log

    # ── GENERATION ────────────────────────────────────────
    try:
        start = time.time()

        result = generate_draft(
            section_name=EVAL_SECTION_NAME,
            user_instruction=question,
            directives_path=directives_path,
            chroma_dir=chroma_dir,
            retrieval_query=question,
            mode="evaluation",
            retrieved_chunks=raw_chunks,
        )

        # generate_draft returns a DraftResult; extract text content
        run_log["answer"] = (
            result.content if hasattr(result, "content") else str(result)
        )
        run_log["generation_time_sec"] = round(time.time() - start, 3)

    except Exception as e:
        run_log.update(status="failed", failed_stage="generation", error_message=str(e))
        run_log["total_pipeline_time_sec"] = round(time.time() - start_total, 3)
        return run_log

    run_log["total_pipeline_time_sec"] = round(time.time() - start_total, 3)
    return run_log


# ─────────────────────────────────────────────────────────
# MAIN  (callable from main.py as main(project_name) or standalone)
# ─────────────────────────────────────────────────────────

def main(project_name: str | None = None):
    """
    Entry point — can be called:
      - programmatically: main("demo_project")
      - via CLI:          python evaluator.py --project demo_project
    """
    # ── ARGUMENT RESOLUTION ───────────────────────────────
    # If called programmatically (from main.py), project_name is already set.
    # If called as a script, parse CLI args.
    if project_name is None:
        parser = argparse.ArgumentParser(description="RAG Evaluation Suite (RAGAS)")
        parser.add_argument(
            "--project",
            required=True,
            help="Project folder name (e.g. demo_project)",
        )
        parser.add_argument(
            "--dataset",
            default=None,
            help=(
                "Path to synthetic_golden_dataset.json "
                "(default: projects/{project}/data/evaluation/synthetic_golden_dataset.json)"
            ),
        )
        args = parser.parse_args()
        project_name  = args.project
        dataset_override = Path(args.dataset) if args.dataset else None
    else:
        dataset_override = None

    print("--- Launching RAG Evaluation Suite ---")
    print(f"[INFO] Project: {project_name}")

    # ── PATHS  (all derived from paths.py / .env) ─────────
    paths      = get_project_paths(project_name)
    output_dir = paths["dataset_evaluation"]   # data/evaluation
    output_dir.mkdir(parents=True, exist_ok=True)

    chroma_dir = str(paths["vector_db"])

    # directives_path is optional — use it if the project has one
    directives_path: Path | None = paths["directives"]
    if not directives_path.exists():
        print(
            f"[WARN] Directives file not found ({directives_path}), "
            "proceeding without it."
        )
        directives_path = None

    # ── DATASET PATH ──────────────────────────────────────
    # Priority: CLI --dataset arg > default location in data/evaluation
    dataset_path = dataset_override or (
        output_dir / SYNTHETIC_DATASET_FILENAME
    )
    golden_dataset = load_golden_dataset(dataset_path)

    # ── RUN PIPELINE ──────────────────────────────────────
    ragas_inputs: dict[str, list] = {
        "eval_id":            [],
        "user_input":         [],
        "response":           [],
        "reference":          [],
        "retrieved_contexts": [],
    }
    telemetry_records: list[dict] = []
    audit_records:     list[dict] = []

    for item in golden_dataset:
        print(
            f"[{item['eval_id']}] "
            f"[{item['category']}] "
            f"{item['question']}"
        )

        run_result = run_monitored_pipeline(
            question=item["question"],
            chroma_dir=chroma_dir,
            directives_path=directives_path,
        )

        retrieval_gt_metrics = calculate_retrieval_ground_truth_metrics(
            item,
            run_result["retrieved_chunks"],
        )

        # Build telemetry record — include optional fields if present
        telemetry_record: dict = {
            "eval_id":                  item["eval_id"],
            "category":                 item["category"],
            "answerable":               item["answerable"],
            "question":                 item["question"],
            "ground_truth":             item["ground_truth"],

            # Optional fields from the evaluation dataset
            "source":                   item.get("source", ""),
            "source_chunk_id":          item.get("source_chunk_id", ""),
            "source_chunk_ids":         item.get("source_chunk_ids", []),
            "source_section":           item.get("source_section", ""),
            "source_sections":          item.get("source_sections", []),

            # Pipeline results
            "status":                   run_result["status"],
            "failed_stage":             run_result["failed_stage"],
            "error_message":            run_result["error_message"],
            "retrieval_time_sec":       run_result["retrieval_time_sec"],
            "generation_time_sec":      run_result["generation_time_sec"],
            "total_pipeline_time_sec":  run_result["total_pipeline_time_sec"],
            "chunks_count":             len(run_result["contexts"]),

            # Deterministic retrieval evaluation
            **retrieval_gt_metrics,

            "evaluation_timestamp":     now_utc(),

            **SYSTEM_CONFIG,
        }
        
        telemetry_records.append(telemetry_record)
        audit_records.append({
            **telemetry_record,
            "answer": run_result["answer"],
            "retrieved_contexts": run_result["contexts"],
            "retrieved_chunks": run_result["retrieved_chunks"],
        })

        if run_result["status"] != "success":
            print(
                f"  -> [Skipped RAGAS] "
                f"Failed at stage: {run_result['failed_stage']}"
            )
            continue

        if item["answerable"] is not True:
            print(
                "  -> [Skipped RAGAS] "
                "Unanswerable case; preserved for manual abstention analysis."
            )
            continue

        ragas_inputs["eval_id"].append(item["eval_id"])
        ragas_inputs["user_input"].append(item["question"])
        ragas_inputs["response"].append(run_result["answer"])
        ragas_inputs["reference"].append(item["ground_truth"])
        ragas_inputs["retrieved_contexts"].append(run_result["contexts"])

    # ── SAVE TELEMETRY ────────────────────────────────────
    telemetry_path = output_dir / "pipeline_telemetry_full.csv"
    audit_path     = output_dir / "rag_audit_full.jsonl"

    pd.DataFrame(telemetry_records).to_csv(telemetry_path, index=False)
    save_jsonl(str(audit_path), audit_records)

    if not ragas_inputs["eval_id"]:
        print(
            "[Critical] No successful pipeline runs available for RAGAS. "
            "Check errors above."
        )
        return

    # ── RAGAS EVALUATION ──────────────────────────────────
    # Build the dataset WITHOUT eval_id — RAGAS doesn't accept custom columns.
    # We keep a parallel list of eval_ids in the same order to re-attach later.
    ragas_eval_ids = ragas_inputs.pop("eval_id")
    dataset = Dataset.from_dict(ragas_inputs)

    evaluator_llm = ChatOpenAI(
        model=SYSTEM_CONFIG["judge_llm_model"],
        temperature=0.0,
    )
    evaluator_embeddings = OpenAIEmbeddings(
        model=SYSTEM_CONFIG["embedding_model"],
    )
    metrics = [faithfulness, answer_relevancy, context_recall, context_precision]

    print("\nCalculating RAGAS metrics...")
    try:
        # Best Practice: Configure RunConfig to limit concurrency and enforce retries
        # This prevents OpenAI from triggering 429 Too Many Requests errors
        secure_config = RunConfig(
            max_workers=1,       # Forces sequential evaluation
            timeout=120,        # Allows up to 120 seconds per evaluation request
            max_retries=10,      # If a 429 occurs, RAGAS will automatically retry
            max_wait=15        # Sets the maximum exponential backoff wait time
        )

        ragas_result = evaluate(
            dataset=dataset,
            metrics=metrics,
            llm=evaluator_llm,
            embeddings=evaluator_embeddings,
            run_config=secure_config,  # Inject the anti-429 configuration block
        )

        df_ragas = ragas_result.to_pandas()
        raw_ragas_path = output_dir / "ragas_raw_results.csv"
        df_ragas.to_csv(raw_ragas_path, index=False)
        print(f"[INFO] Raw RAGAS results saved: {raw_ragas_path}")
    except Exception as e:
        print(f"[Critical] RAGAS evaluation failed: {e}")
        return

    # ── MERGE & SAVE RESULTS ──────────────────────────────
    # Re-attach eval_id to df_ragas by index (same order as ragas_inputs).
    df_ragas = df_ragas.copy()
    df_ragas["eval_id"] = ragas_eval_ids

    # Build telemetry only for the successful runs that went through RAGAS.
    successful_ids = set(ragas_eval_ids)
    df_telemetry = pd.DataFrame(
        [r for r in telemetry_records if r["eval_id"] in successful_ids]
    )
    df_final = pd.merge(df_ragas, df_telemetry, on="eval_id", how="left")

    scorecard_path          = output_dir / "evaluation_scorecard.csv"
    scorecard_jsonl_path    = output_dir / "evaluation_scorecard.jsonl"
    category_summary_path   = output_dir / "evaluation_category_summary.csv"

    df_final.to_csv(scorecard_path, index=False)
    save_jsonl(str(scorecard_jsonl_path), df_final.to_dict(orient="records"))

    expected_metric_columns = [
    "faithfulness",
    "answer_relevancy",
    "context_recall",
    "context_precision",
    ]

    metric_columns = [
        col for col in expected_metric_columns
        if col in df_final.columns
    ]

    if metric_columns:
        df_category_summary = (
            df_final.groupby("category")[metric_columns]
            .mean(numeric_only=True)
            .reset_index()
        )
        df_category_summary.to_csv(category_summary_path, index=False)
    else:
        df_category_summary = pd.DataFrame()
        print("[WARN] No RAGAS metric columns found for category summary.")

    # ── PRINT SCORECARD ───────────────────────────────────
    print("\n=======================================================")
    print("              RAG SYSTEM EVALUATION SCORECARD          ")
    print("=======================================================")

    def print_existing_columns(title: str, columns: list[str]):
        existing_columns = [col for col in columns if col in df_final.columns]

        print(f"\n[{title}]")

        if existing_columns:
            print(df_final[existing_columns].to_string(index=False))
        else:
            print("[WARN] No available columns to print.")

    print_existing_columns(
        "RETRIEVAL METRICS",
        [
            "eval_id",
            "category",
            "context_precision",
            "context_recall",
            "retrieval_time_sec",
            "chunks_count",
        ],
    )

    print_existing_columns(
        "GENERATION METRICS",
        [
            "eval_id",
            "category",
            "faithfulness",
            "answer_relevancy",
            "generation_time_sec",
        ],
    )

    print("\n[CATEGORY SUMMARY]")
    if not df_category_summary.empty:
        print(df_category_summary.to_string(index=False))
    else:
        print("[WARN] Category summary not available.")

    print("\n[OUTPUT FILES]")
    print(f"  Scorecard CSV        : {scorecard_path}")
    print(f"  Scorecard JSONL      : {scorecard_jsonl_path}")
    print(f"  Full telemetry CSV   : {telemetry_path}")
    print(f"  Full audit JSONL     : {audit_path}")
    print(f"  Category summary CSV : {category_summary_path}")

if __name__ == "__main__":
    main()
